feat: add static build to ci
Former-commit-id: 61a045bd334fa1dac3f78fcf2133cd52c4536e07

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,8 +45,8 @@ jobs:
       - name: Check static build of the linux version
         run: |
           if ldd croc-linux-amd64 2>&1 | grep -q "not a dynamic executable"; then
-        echo "Static build confirmed."
+            echo "Static build confirmed."
           else
-        echo "Error: croc-linux-amd64 is a dynamic executable."
-        exit 1
+            echo "Error: croc-linux-amd64 is a dynamic executable."
+            exit 1
           fi
